### ISSUE TITLE
Index is inefficient warning

### ISSUE THREAD

**Issue by lukerandall** [treojs/treo-websql#1]
Using treo-websql, we've noticed the warnings about index being inefficient, and looking at it see that it uses a cursor. However, in [shim.js](https://github.com/treojs/treo-websql/blob/master/lib/shim.js#L637-L688), find converts an IDBKeyRange to a (presumably somewhat more efficient) WHERE clause.

What are the reasons for using cursor to implement index over using a WHERE clause? Is it just a matter of writing code, or are there other considerations of which I am ignorant?

**Comment by alekseykulikov** [comment]
You're right. It's inefficient, because it uses cursor, instead of `WHERE`.
I did this because I needed support of multi-indexes, and it's clearly a **hack**. Let's use #2 to discuss alternative solutions.
